-- =============================================================================
-- PROYECTO: SAMANYA OS
-- ARCHIVO: build_all.sql
-- DESCRIPCIÓN: Script maestro orquestador de compilación PL/SQL.
--              Invoca secuencialmente cada uno de los 94 artefactos PL/SQL
--              en su orden lógico de dependencias utilizando directivas relativas "@@".
--              Compatible con SQL*Plus, SQLcl, Oracle SQL Developer y scripts de migración.
--
--              Estructura de Artefactos (94 objetos):
--              - 1 Función base de fecha (f_fecha_actual.sql)
--              - 87 Paquetes DAO de acceso a datos (pkgsmy_*_dao.sql)
--              - 1 Paquete de utilidades de excepciones/logging (uti_ge_excepciones_pkg.sql)
--              - 1 Paquete de consultas y filtros (pkgca_residentes.sql)
--              - 1 Paquete de lógica funcional pura (pkgln_archivos.sql)
--              - 3 Paquetes transaccionales de negocio (pkgcn_auth.sql, pkgcn_consentimientos.sql, pkgcn_archivos.sql)
--              - 1 Bloque final de verificación y reporte de objetos inválidos en USER_OBJECTS
-- =============================================================================

SET SERVEROUTPUT ON SIZE UNLIMITED;
SET FEEDBACK ON;
SET VERIFY OFF;
SET LINESIZE 200;
SET PAGESIZE 100;

-- -----------------------------------------------------------------------------
-- INICIO DE COMPILACIÓN Y REGISTRO DE HORA OFICIAL (UTC-5 Bogotá)
-- -----------------------------------------------------------------------------
DECLARE
    v_fecha_bogota VARCHAR2(50);
BEGIN
    SELECT TO_CHAR(CAST(SYSTIMESTAMP AT TIME ZONE '-05:00' AS DATE), 'YYYY-MM-DD HH24:MI:SS')
      INTO v_fecha_bogota
      FROM DUAL;
    DBMS_OUTPUT.PUT_LINE('============================================================================');
    DBMS_OUTPUT.PUT_LINE('  INICIANDO COMPILACIÓN COMPLETA DE ARTEFACTOS PL/SQL - SAMANYA OS');
    DBMS_OUTPUT.PUT_LINE('  TOTAL OBJETOS A COMPILAR: 94');
    DBMS_OUTPUT.PUT_LINE('  HORA OFICIAL (Bogotá, Colombia - UTC-5): ' || v_fecha_bogota);
    DBMS_OUTPUT.PUT_LINE('============================================================================');
END;
/

PROMPT
PROMPT ============================================================================
PROMPT [1/6] COMPILANDO FUNCIONES Y UTILIDADES BASE
PROMPT ============================================================================
PROMPT >> [01/94] Compilando f_fecha_actual.sql...
@@f_fecha_actual.sql

PROMPT
PROMPT ============================================================================
PROMPT [2/6] COMPILANDO CAPA DE ACCESO A DATOS (87 PAQUETES DAO)
PROMPT ============================================================================
PROMPT >> [02/94] Compilando pkgsmy_acudientes_dao.sql...
@@pkgsmy_acudientes_dao.sql
PROMPT >> [03/94] Compilando pkgsmy_alcances_tareas_dao.sql...
@@pkgsmy_alcances_tareas_dao.sql
PROMPT >> [04/94] Compilando pkgsmy_archivos_dao.sql...
@@pkgsmy_archivos_dao.sql
PROMPT >> [05/94] Compilando pkgsmy_areas_empleados_dao.sql...
@@pkgsmy_areas_empleados_dao.sql
PROMPT >> [06/94] Compilando pkgsmy_auditoria_accesos_dao.sql...
@@pkgsmy_auditoria_accesos_dao.sql
PROMPT >> [07/94] Compilando pkgsmy_bitacora_residente_dao.sql...
@@pkgsmy_bitacora_residente_dao.sql
PROMPT >> [08/94] Compilando pkgsmy_canales_notificacion_dao.sql...
@@pkgsmy_canales_notificacion_dao.sql
PROMPT >> [09/94] Compilando pkgsmy_cargos_empleados_dao.sql...
@@pkgsmy_cargos_empleados_dao.sql
PROMPT >> [10/94] Compilando pkgsmy_categorias_bitacora_dao.sql...
@@pkgsmy_categorias_bitacora_dao.sql
PROMPT >> [11/94] Compilando pkgsmy_categorias_doc_clinicos_dao.sql...
@@pkgsmy_categorias_doc_clinicos_dao.sql
PROMPT >> [12/94] Compilando pkgsmy_centros_dao.sql...
@@pkgsmy_centros_dao.sql
PROMPT >> [13/94] Compilando pkgsmy_chat_participantes_dao.sql...
@@pkgsmy_chat_participantes_dao.sql
PROMPT >> [14/94] Compilando pkgsmy_clases_archivos_dao.sql...
@@pkgsmy_clases_archivos_dao.sql
PROMPT >> [15/94] Compilando pkgsmy_consentimiento_destinatarios_dao.sql...
@@pkgsmy_consentimiento_destinatarios_dao.sql
PROMPT >> [16/94] Compilando pkgsmy_consentimientos_dao.sql...
@@pkgsmy_consentimientos_dao.sql
PROMPT >> [17/94] Compilando pkgsmy_consistencias_dieta_dao.sql...
@@pkgsmy_consistencias_dieta_dao.sql
PROMPT >> [18/94] Compilando pkgsmy_conversaciones_chat_dao.sql...
@@pkgsmy_conversaciones_chat_dao.sql
PROMPT >> [19/94] Compilando pkgsmy_dispositivos_push_dao.sql...
@@pkgsmy_dispositivos_push_dao.sql
PROMPT >> [20/94] Compilando pkgsmy_documentos_clinicos_dao.sql...
@@pkgsmy_documentos_clinicos_dao.sql
PROMPT >> [21/94] Compilando pkgsmy_documentos_eliminados_log_dao.sql...
@@pkgsmy_documentos_eliminados_log_dao.sql
PROMPT >> [22/94] Compilando pkgsmy_documentos_empleado_dao.sql...
@@pkgsmy_documentos_empleado_dao.sql
PROMPT >> [23/94] Compilando pkgsmy_empleados_dao.sql...
@@pkgsmy_empleados_dao.sql
PROMPT >> [24/94] Compilando pkgsmy_errores_dao.sql...
@@pkgsmy_errores_dao.sql
PROMPT >> [25/94] Compilando pkgsmy_estados_admin_med_dao.sql...
@@pkgsmy_estados_admin_med_dao.sql
PROMPT >> [26/94] Compilando pkgsmy_estados_archivos_dao.sql...
@@pkgsmy_estados_archivos_dao.sql
PROMPT >> [27/94] Compilando pkgsmy_estados_consentimientos_dao.sql...
@@pkgsmy_estados_consentimientos_dao.sql
PROMPT >> [28/94] Compilando pkgsmy_estados_doc_clinicos_dao.sql...
@@pkgsmy_estados_doc_clinicos_dao.sql
PROMPT >> [29/94] Compilando pkgsmy_estados_empleados_dao.sql...
@@pkgsmy_estados_empleados_dao.sql
PROMPT >> [30/94] Compilando pkgsmy_estados_firmas_cons_dao.sql...
@@pkgsmy_estados_firmas_cons_dao.sql
PROMPT >> [31/94] Compilando pkgsmy_estados_incidentes_dao.sql...
@@pkgsmy_estados_incidentes_dao.sql
PROMPT >> [32/94] Compilando pkgsmy_estados_medicamentos_dao.sql...
@@pkgsmy_estados_medicamentos_dao.sql
PROMPT >> [33/94] Compilando pkgsmy_estados_pagos_dao.sql...
@@pkgsmy_estados_pagos_dao.sql
PROMPT >> [34/94] Compilando pkgsmy_estados_parametros_dao.sql...
@@pkgsmy_estados_parametros_dao.sql
PROMPT >> [35/94] Compilando pkgsmy_estados_permisos_dao.sql...
@@pkgsmy_estados_permisos_dao.sql
PROMPT >> [36/94] Compilando pkgsmy_estados_plantillas_turno_dao.sql...
@@pkgsmy_estados_plantillas_turno_dao.sql
PROMPT >> [37/94] Compilando pkgsmy_estados_residentes_dao.sql...
@@pkgsmy_estados_residentes_dao.sql
PROMPT >> [38/94] Compilando pkgsmy_estados_roles_dao.sql...
@@pkgsmy_estados_roles_dao.sql
PROMPT >> [39/94] Compilando pkgsmy_estados_solicitudes_adm_dao.sql...
@@pkgsmy_estados_solicitudes_adm_dao.sql
PROMPT >> [40/94] Compilando pkgsmy_estados_tareas_dao.sql...
@@pkgsmy_estados_tareas_dao.sql
PROMPT >> [41/94] Compilando pkgsmy_estados_turnos_dao.sql...
@@pkgsmy_estados_turnos_dao.sql
PROMPT >> [42/94] Compilando pkgsmy_estados_usuarios_dao.sql...
@@pkgsmy_estados_usuarios_dao.sql
PROMPT >> [43/94] Compilando pkgsmy_eventos_calendario_dao.sql...
@@pkgsmy_eventos_calendario_dao.sql
PROMPT >> [44/94] Compilando pkgsmy_generos_dao.sql...
@@pkgsmy_generos_dao.sql
PROMPT >> [45/94] Compilando pkgsmy_historias_clinicas_dao.sql...
@@pkgsmy_historias_clinicas_dao.sql
PROMPT >> [46/94] Compilando pkgsmy_incidente_residentes_dao.sql...
@@pkgsmy_incidente_residentes_dao.sql
PROMPT >> [47/94] Compilando pkgsmy_incidentes_dao.sql...
@@pkgsmy_incidentes_dao.sql
PROMPT >> [48/94] Compilando pkgsmy_medicamentos_prescritos_dao.sql...
@@pkgsmy_medicamentos_prescritos_dao.sql
PROMPT >> [49/94] Compilando pkgsmy_mensajes_chat_dao.sql...
@@pkgsmy_mensajes_chat_dao.sql
PROMPT >> [50/94] Compilando pkgsmy_niveles_movilidad_dao.sql...
@@pkgsmy_niveles_movilidad_dao.sql
PROMPT >> [51/94] Compilando pkgsmy_notificaciones_sistema_dao.sql...
@@pkgsmy_notificaciones_sistema_dao.sql
PROMPT >> [52/94] Compilando pkgsmy_parametros_dao.sql...
@@pkgsmy_parametros_dao.sql
PROMPT >> [53/94] Compilando pkgsmy_parentescos_dao.sql...
@@pkgsmy_parentescos_dao.sql
PROMPT >> [54/94] Compilando pkgsmy_planes_nutricionales_dao.sql...
@@pkgsmy_planes_nutricionales_dao.sql
PROMPT >> [55/94] Compilando pkgsmy_plantillas_turno_dao.sql...
@@pkgsmy_plantillas_turno_dao.sql
PROMPT >> [56/94] Compilando pkgsmy_registros_admin_med_dao.sql...
@@pkgsmy_registros_admin_med_dao.sql
PROMPT >> [57/94] Compilando pkgsmy_registros_alim_detalle_dao.sql...
@@pkgsmy_registros_alim_detalle_dao.sql
PROMPT >> [58/94] Compilando pkgsmy_registros_alim_sesion_dao.sql...
@@pkgsmy_registros_alim_sesion_dao.sql
PROMPT >> [59/94] Compilando pkgsmy_residente_acudiente_dao.sql...
@@pkgsmy_residente_acudiente_dao.sql
PROMPT >> [60/94] Compilando pkgsmy_residentes_dao.sql...
@@pkgsmy_residentes_dao.sql
PROMPT >> [61/94] Compilando pkgsmy_roles_dao.sql...
@@pkgsmy_roles_dao.sql
PROMPT >> [62/94] Compilando pkgsmy_roles_en_incidente_dao.sql...
@@pkgsmy_roles_en_incidente_dao.sql
PROMPT >> [63/94] Compilando pkgsmy_severidades_incidentes_dao.sql...
@@pkgsmy_severidades_incidentes_dao.sql
PROMPT >> [64/94] Compilando pkgsmy_signos_vitales_dao.sql...
@@pkgsmy_signos_vitales_dao.sql
PROMPT >> [65/94] Compilando pkgsmy_solicitud_adm_contactos_dao.sql...
@@pkgsmy_solicitud_adm_contactos_dao.sql
PROMPT >> [66/94] Compilando pkgsmy_solicitudes_admision_dao.sql...
@@pkgsmy_solicitudes_admision_dao.sql
PROMPT >> [67/94] Compilando pkgsmy_solicitudes_permisos_dao.sql...
@@pkgsmy_solicitudes_permisos_dao.sql
PROMPT >> [68/94] Compilando pkgsmy_suministros_registro_dao.sql...
@@pkgsmy_suministros_registro_dao.sql
PROMPT >> [69/94] Compilando pkgsmy_tarea_residentes_dao.sql...
@@pkgsmy_tarea_residentes_dao.sql
PROMPT >> [70/94] Compilando pkgsmy_tareas_operativas_dao.sql...
@@pkgsmy_tareas_operativas_dao.sql
PROMPT >> [71/94] Compilando pkgsmy_tipos_adjuntos_chat_dao.sql...
@@pkgsmy_tipos_adjuntos_chat_dao.sql
PROMPT >> [72/94] Compilando pkgsmy_tipos_archivos_doc_dao.sql...
@@pkgsmy_tipos_archivos_doc_dao.sql
PROMPT >> [73/94] Compilando pkgsmy_tipos_canales_chat_dao.sql...
@@pkgsmy_tipos_canales_chat_dao.sql
PROMPT >> [74/94] Compilando pkgsmy_tipos_comidas_dao.sql...
@@pkgsmy_tipos_comidas_dao.sql
PROMPT >> [75/94] Compilando pkgsmy_tipos_consentimientos_dao.sql...
@@pkgsmy_tipos_consentimientos_dao.sql
PROMPT >> [76/94] Compilando pkgsmy_tipos_dietas_dao.sql...
@@pkgsmy_tipos_dietas_dao.sql
PROMPT >> [77/94] Compilando pkgsmy_tipos_entradas_doc_dao.sql...
@@pkgsmy_tipos_entradas_doc_dao.sql
PROMPT >> [78/94] Compilando pkgsmy_tipos_eventos_dao.sql...
@@pkgsmy_tipos_eventos_dao.sql
PROMPT >> [79/94] Compilando pkgsmy_tipos_identificacion_dao.sql...
@@pkgsmy_tipos_identificacion_dao.sql
PROMPT >> [80/94] Compilando pkgsmy_tipos_incidentes_dao.sql...
@@pkgsmy_tipos_incidentes_dao.sql
PROMPT >> [81/94] Compilando pkgsmy_tipos_notificaciones_dao.sql...
@@pkgsmy_tipos_notificaciones_dao.sql
PROMPT >> [82/94] Compilando pkgsmy_tipos_permisos_dao.sql...
@@pkgsmy_tipos_permisos_dao.sql
PROMPT >> [83/94] Compilando pkgsmy_tipos_suministros_dao.sql...
@@pkgsmy_tipos_suministros_dao.sql
PROMPT >> [84/94] Compilando pkgsmy_tipos_tareas_dao.sql...
@@pkgsmy_tipos_tareas_dao.sql
PROMPT >> [85/94] Compilando pkgsmy_tipos_usuarios_dao.sql...
@@pkgsmy_tipos_usuarios_dao.sql
PROMPT >> [86/94] Compilando pkgsmy_turnos_asignados_dao.sql...
@@pkgsmy_turnos_asignados_dao.sql
PROMPT >> [87/94] Compilando pkgsmy_usuarios_dao.sql...
@@pkgsmy_usuarios_dao.sql
PROMPT >> [88/94] Compilando pkgsmy_vias_administracion_dao.sql...
@@pkgsmy_vias_administracion_dao.sql

PROMPT
PROMPT ============================================================================
PROMPT [3/6] COMPILANDO PAQUETE DE GESTIÓN DE EXCEPCIONES Y LOGGING
PROMPT ============================================================================
PROMPT >> [89/94] Compilando uti_ge_excepciones_pkg.sql...
@@uti_ge_excepciones_pkg.sql

PROMPT
PROMPT ============================================================================
PROMPT [4/6] COMPILANDO CAPA DE CONSULTAS Y VISTAS (PKGCA)
PROMPT ============================================================================
PROMPT >> [90/94] Compilando pkgca_residentes.sql...
@@pkgca_residentes.sql

PROMPT
PROMPT ============================================================================
PROMPT [5/6] COMPILANDO CAPA DE LÓGICA FUNCIONAL PURA (PKGLN)
PROMPT ============================================================================
PROMPT >> [91/94] Compilando pkgln_archivos.sql...
@@pkgln_archivos.sql

PROMPT
PROMPT ============================================================================
PROMPT [6/6] COMPILANDO CAPA TRANSACCIONAL DE NEGOCIO (PKGCN)
PROMPT ============================================================================
PROMPT >> [92/94] Compilando pkgcn_auth.sql...
@@pkgcn_auth.sql
PROMPT >> [93/94] Compilando pkgcn_consentimientos.sql...
@@pkgcn_consentimientos.sql
PROMPT >> [94/94] Compilando pkgcn_archivos.sql...
@@pkgcn_archivos.sql

PROMPT
PROMPT ============================================================================
PROMPT VALIDACIÓN DE ESTADO Y OBJETOS INVÁLIDOS EN EL ESQUEMA
PROMPT ============================================================================
DECLARE
    vn_invalidos NUMBER := 0;
BEGIN
    FOR reg IN (
        SELECT object_type, object_name, status
          FROM user_objects
         WHERE status = 'INVALID'
           AND (object_name LIKE 'PKGSMY_%_DAO' 
                OR object_name LIKE 'PKGCA_%' 
                OR object_name LIKE 'PKGCN_%'
                OR object_name LIKE 'PKGLN_%'
                OR object_name = 'UTI_GE_EXCEPCIONES_PKG'
                OR object_name = 'F_FECHA_ACTUAL')
         ORDER BY object_type, object_name
    ) LOOP
        vn_invalidos := vn_invalidos + 1;
        DBMS_OUTPUT.PUT_LINE('  ALERTA: Objeto ' || reg.object_type || ' ' || reg.object_name || ' tiene estado ' || reg.status);
    END LOOP;

    IF vn_invalidos = 0 THEN
        DBMS_OUTPUT.PUT_LINE('============================================================================');
        DBMS_OUTPUT.PUT_LINE('  OK: Todos los 94 objetos PL/SQL se encuentran en estado VALID.');
        DBMS_OUTPUT.PUT_LINE('============================================================================');
    ELSE
        DBMS_OUTPUT.PUT_LINE('============================================================================');
        DBMS_OUTPUT.PUT_LINE('  ATENCIÓN: Se detectaron ' || vn_invalidos || ' objetos en estado INVALID.');
        DBMS_OUTPUT.PUT_LINE('============================================================================');
    END IF;
END;
/

-- -----------------------------------------------------------------------------
-- RESUMEN FINAL DE COMPILACIÓN
-- -----------------------------------------------------------------------------
DECLARE
    v_fecha_fin VARCHAR2(50);
BEGIN
    SELECT TO_CHAR(CAST(SYSTIMESTAMP AT TIME ZONE '-05:00' AS DATE), 'YYYY-MM-DD HH24:MI:SS')
      INTO v_fecha_fin
      FROM DUAL;
    DBMS_OUTPUT.PUT_LINE('============================================================================');
    DBMS_OUTPUT.PUT_LINE('  COMPILACIÓN COMPLETADA - HORA BOGOTÁ (UTC-5): ' || v_fecha_fin);
    DBMS_OUTPUT.PUT_LINE('  Total objetos orquestados: 94');
    DBMS_OUTPUT.PUT_LINE('  (1 Función + 87 DAOs + 1 Utilidad Logging + 1 Consulta PKGCA + 1 Lógica Pura PKGLN + 3 Transaccionales PKGCN)');
    DBMS_OUTPUT.PUT_LINE('============================================================================');
END;
/
